name: Deploy and Run Databricks Bundle

on:
  push:
    branches:
      - main

jobs:
  deploy-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Databricks CLI and Bundles plugin
        run: |
          python -m pip install --upgrade pip
          pip install databricks-cli
          pip install databricks-bundle-cli

      - name: Configure Databricks CLI
        run: |
          databricks configure --token <<EOF
          ${{ secrets.DATABRICKS_HOST }}
          ${{ secrets.DATABRICKS_TOKEN }}
          EOF

      - name: Validate Databricks bundle
        run: databricks bundle validate --target dev

      - name: Deploy Databricks bundle
        run: databricks bundle deploy --target dev

      - name: Run Databricks job
        run: databricks bundle run demo_bundle_job --target dev
